name: Weekly Markdown Log

on:
  push:
    branches:
      - main  # Adjust this if your main branch is named differently
  schedule:
    - cron: '0 12 * * 5'  # Run every Friday at 12:00 PM (UTC)

jobs:
  create-log:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install pyyaml markdown

      # Step 4: Get new Markdown files created in the last week in docs folder
      - name: Get new Markdown files from the last week in docs folder
        id: get_new_files
        run: |
          # Get the list of Markdown files added in the last 7 days in the docs folder
          last_week_files=$(git log --since="7 days ago" --pretty="" --name-only --diff-filter=A -- docs/topics/*.md | grep -v "index.md" | sort | uniq)
          
          # Print the list of files found for debugging
          echo "Files found: $last_week_files"
          
          # If no new files are found, set the variable to 'none'
          if [ -z "$last_week_files" ]; then
            last_week_files="none"
          fi
          
          # Set the environment variable for the next step
          echo "NEW_MARKDOWN_FILES=$last_week_files" >> $GITHUB_ENV

      # Step 5: Run the Python script to create the log
      - name: Run log creation script
        run: python createLog.py

      # Step 6: Commit and Push Log File
      - name: Commit and Push Log File
        run: |
          git config --local user.email "levoxtrip@gmail.com"
          git config --local user.name "levoxtrip"
          git add log.md
          git commit -m "Weekly log update - $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
