name: Weekly Markdown Log

on:
  schedule:
    - cron: '0 12 * * 5'  # Run every Friday at 12:00 PM (UTC)

jobs:
  create-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install pyyaml markdown

      - name: Get new Markdown files from the last week in docs/topics folder, excluding index.md files
        id: get_new_files
        run: |
          last_week_files=$(git log --since="7 days ago" --pretty="" --name-only --diff-filter=A -- docs/topics/*.md | grep -v "index.md" | sort | uniq)

          echo "Files found: $last_week_files"
          
          # Replace newlines with spaces and escape quotes
          escaped_files=$(echo "$last_week_files" | tr '\n' ' ' | sed 's/\"/\\"/g')
          
          # If no new files are found, set the variable to 'none'
          if [ -z "$escaped_files" ]; then
            escaped_files="none"
          fi
          
          # Set the environment variable for the next step
          echo "NEW_MARKDOWN_FILES=\"$escaped_files\"" >> $GITHUB_ENV

      # Step 5: Run the Python script to create the log
      - name: Run log creation script
        run: python createLog.py

      # Step 6: Commit and Push Log File
      - name: Commit and Push Log File
        run: |
          git config --local user.email "levoxtrip@gmail.com"
          git config --local user.name "levoxtrip"
          git add log.md
          git commit -m "Weekly log update - $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
