name: Weekly Markdown Log Test

on:
  push:
    branches:
      - main

jobs:
  create-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install pyyaml markdown

      - name: Get newly added Markdown files from the last week in docs/topics folder
        id: get_new_files
        run: |
          # Get all markdown files that have been added in the last 7 days
          last_week_files=$(git log --diff-filter=A --since=7 days --name-only -- docs/topics/ | grep '\.md$' | grep -v "index.md")

          echo "Files added in the last week: $last_week_files"

          # If no new files were found, set the variable to 'none'
          if [ -z "$last_week_files" ]; then
            last_week_files="none"
          fi

          # Set the environment variable for the next step
          echo "NEW_MARKDOWN_FILES=\"$last_week_files\"" >> $GITHUB_ENV

      - name: Run log creation script
        run: python createLog.py

      - name: Commit and Push Log File
        run: |
          git config --local user.email "levoxtrip@gmail.com"
          git config --local user.name "levoxtrip"
          git add log.md
          git commit -m "Weekly log update - $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
