name: Generate Newsletter on Push

on:
  push:
    branches:
      - main  # Replace with your target branch
    paths-ignore:
      - 'newsletter.md'  # Prevent recursion when the action commits newsletter.md

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Set up date utility
        run: |
          sudo apt-get update && sudo apt-get install -y coreutils
          
      - name: Generate newsletter of new .md files
        shell: bash
        run: |
          #!/bin/bash

          # Get the date and time for one week ago in ISO 8601 format
          one_week_ago=$(date -d "7 days ago" --iso-8601=seconds)

          # Initialize an array to hold new files
          new_files=()

          # Get a list of all .md files tracked by Git
          all_md_files=$(git ls-files '*.md')

          # Loop over each .md file
          for file in $all_md_files; do
              # Get the first commit date of the file in ISO 8601 format
              first_commit_date=$(git log --diff-filter=A --follow --format="%aI" -- "$file" | tail -1)
              
              # If the first commit date is after one week ago, add to new_files
              if [[ "$first_commit_date" > "$one_week_ago" ]]; then
                  new_files+=("$file")
              fi
          done

          # Generate the newsletter content
          if [ ${#new_files[@]} -eq 0 ]; then
              echo "No new markdown files added in the last week." > newsletter.md
          else
              {
                  echo "# Weekly Newsletter"
                  echo "## Newly Added Files (Last Week)"
                  for file in "${new_files[@]}"; do
                      echo "- $file"
                  done
              } > newsletter.md
          fi

      - name: Commit and push newsletter
        run: |
          git config --global user.name "levoxtrip"
          git config --global user.email "levoxtrip@gmail.com"
          git add newsletter.md
          git commit -m "Add weekly newsletter"
          git push
        env:
          GIT_AUTHOR_DATE: "$(date)"
          GIT_COMMITTER_DATE: "$(date)"
